# NUMPY

In [3]:
import numpy as np

In [4]:
my_list=[1,2,3,4]
arr=np.array(my_list)

In [6]:
type(arr)

numpy.ndarray

In [15]:
a=np.array([[1,2,3],[4,5,6]])#2D array
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a.ndim #Shows the number of dimensions 

2

In [17]:
a.shape  #Shows the shape of an array

(2, 3)

In [18]:
b=np.array([[1,2,3,4],[2,3,4,5],[3,4,5,6]])
b #2D array

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [20]:
b.ndim

2

In [22]:
b.shape

(3, 4)

In [25]:
c=np.array([[[1,2,3,4],[2,3,4,5]],[[3,4,5,6],[4,5,6,7]]])
c

array([[[1, 2, 3, 4],
        [2, 3, 4, 5]],

       [[3, 4, 5, 6],
        [4, 5, 6, 7]]])

In [26]:
c.ndim

3

In [27]:
c.shape

(2, 2, 4)

In [38]:
# Zero Matrix
a=np.zeros((3,3))    #Generating Zero in a matrix based on given size.
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [39]:
b=np.linspace(0,6,8)    #Linspace is for dividing the values equally.

In [40]:
b

array([0.        , 0.85714286, 1.71428571, 2.57142857, 3.42857143,
       4.28571429, 5.14285714, 6.        ])

In [46]:
#Identity Matrix
c=np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Slicing

In [48]:
a=np.arange(6)

In [50]:
a

array([0, 1, 2, 3, 4, 5])

In [51]:
a[:3]

array([0, 1, 2])

In [52]:
a[2:]

array([2, 3, 4, 5])

In [53]:
a[::2]

array([0, 2, 4])

# Random values.

In [56]:
r1=np.random.rand(4)  # It gives the random numbers between 0 to 1.
r1

array([0.24801636, 0.41773443, 0.04186024, 0.54357372])

In [60]:
r2=np.random.randn(4) #It gives the whole numbers as random numbers
r2

array([-0.22372433,  0.65322098,  0.04677825, -0.42288944])

In [72]:
r3=np.random.randint(0,6,8) # It gives 8 random integers from 0 to 6 but not 6.
r3

array([4, 3, 0, 5, 0, 4, 2, 2])