In [2]:
import numpy as np

In [3]:
a=np.array([[1,1],[3,3]])
a

array([[1, 1],
       [3, 3]])

In [4]:
a.sum(axis=1)

array([2, 6])

In [6]:
a.sum(axis=0)

array([4, 4])

In [7]:
b=np.array([1,2,3,2,1,4,5])
b.max()

5

In [8]:
b.argmax()

6

In [10]:
b.argmin()

0

In [11]:
import csv

In [16]:
data=np.loadtxt("Student_Marks.csv")

ValueError: could not convert string to float: 'number_courses,time_study,Marks'

In [35]:
c=np.random.randint(1,2000,(100,3))

In [36]:
c

array([[1188,  470,  950],
       [ 451, 1372, 1374],
       [  38,  930,  921],
       [ 419,  204, 1835],
       [1363, 1747,   36],
       [ 637, 1496,  340],
       [ 212, 1982, 1746],
       [ 405,  651,  115],
       [ 254,  994, 1134],
       [1818,  358, 1461],
       [ 660, 1659, 1238],
       [ 778,  720,  539],
       [1925,  893, 1524],
       [1328, 1856,  229],
       [1778, 1947, 1177],
       [ 696,  977, 1007],
       [ 770,  329, 1093],
       [1478, 1971, 1093],
       [1220,  778, 1773],
       [ 542, 1248, 1280],
       [1106, 1968,  965],
       [ 889, 1253,  360],
       [ 930, 1708, 1056],
       [ 972, 1364, 1974],
       [ 262, 1284, 1380],
       [ 759,  335, 1094],
       [ 659,  582,  919],
       [1467, 1851, 1925],
       [1446,  851, 1377],
       [ 358, 1098, 1725],
       [1035, 1521,  922],
       [1974,  509,  619],
       [ 565, 1444, 1232],
       [1032, 1192, 1843],
       [ 723, 1904, 1498],
       [ 763, 1919, 1894],
       [ 103,  382,  645],
 

In [37]:
data=c


In [38]:
v=data[:80,::-1]

In [39]:
v

array([[ 950,  470, 1188],
       [1374, 1372,  451],
       [ 921,  930,   38],
       [1835,  204,  419],
       [  36, 1747, 1363],
       [ 340, 1496,  637],
       [1746, 1982,  212],
       [ 115,  651,  405],
       [1134,  994,  254],
       [1461,  358, 1818],
       [1238, 1659,  660],
       [ 539,  720,  778],
       [1524,  893, 1925],
       [ 229, 1856, 1328],
       [1177, 1947, 1778],
       [1007,  977,  696],
       [1093,  329,  770],
       [1093, 1971, 1478],
       [1773,  778, 1220],
       [1280, 1248,  542],
       [ 965, 1968, 1106],
       [ 360, 1253,  889],
       [1056, 1708,  930],
       [1974, 1364,  972],
       [1380, 1284,  262],
       [1094,  335,  759],
       [ 919,  582,  659],
       [1925, 1851, 1467],
       [1377,  851, 1446],
       [1725, 1098,  358],
       [ 922, 1521, 1035],
       [ 619,  509, 1974],
       [1232, 1444,  565],
       [1843, 1192, 1032],
       [1498, 1904,  723],
       [1894, 1919,  763],
       [ 645,  382,  103],
 

In [50]:
q=range(1000)
q

%timeit [i//2 for i in q]

57.5 µs ± 915 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [51]:
p=np.arange(1000)
%timeit p//2

1.98 µs ± 69.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
