In [1]:
import numpy as np

#### 1-D Array

In [13]:
lis=[1,2,3,4]
type(lis)

list

In [14]:
nump=np.array(lis)
type(nump)

numpy.ndarray

#### 2-D Array

In [24]:
two_D=[[1,2,3],[2,3,4],[3,4,51]]
a=np.array(two_D)
a

array([[ 1,  2,  3],
       [ 2,  3,  4],
       [ 3,  4, 51]])

In [25]:
a.ndim

2

In [26]:
a.shape

(3, 3)

#### 3-D Array

In [27]:
three_D=[[[1,2,3],[2,3,4]],[[4,5,5],[7,8,9]]]
b=np.array(three_D)
b

array([[[1, 2, 3],
        [2, 3, 4]],

       [[4, 5, 5],
        [7, 8, 9]]])

In [28]:
b.ndim

3

In [29]:
b.shape

(2, 2, 3)

### ------------------------------------------------------------------------------------------------------------------------------

In [31]:
z=np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
l=np.linspace(0,40,5)
l

array([ 0., 10., 20., 30., 40.])

In [50]:
e=np.eye(4)
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Random numbers

In [55]:
np.random.rand(4,3)

array([[0.51551475, 0.50423308, 0.01751805],
       [0.6454586 , 0.12171055, 0.37349892],
       [0.46934005, 0.63077327, 0.84310825],
       [0.86580742, 0.11470197, 0.25532001]])

In [56]:
np.random.randn(4,3)

array([[-0.93621269,  1.72759894,  1.13351015],
       [ 0.2608888 ,  0.9617541 ,  0.88614613],
       [-0.43246019,  0.84279667,  0.71778817],
       [-0.59103904, -1.03654081, -0.23290278]])

In [60]:
r=np.random.randint(1,16,(4,3))
r

array([[ 6, 13, 10],
       [ 2, 14, 12],
       [ 2,  6,  7],
       [ 5,  3,  6]])

In [62]:
r[0:2,0:2]

array([[ 6, 13],
       [ 2, 14]])

In [63]:
r.reshape(3,4)

array([[ 6, 13, 10,  2],
       [14, 12,  2,  6],
       [ 7,  5,  3,  6]])

In [66]:
r[3]

array([5, 3, 6])

In [67]:
np.sum(r[3])

14

In [73]:
r[3].argmax() # Shows the maximum value's index.

2

In [74]:
r[3].argmin() # Shows the minimum value's index.

1

In [79]:
d=np.random.randint(1,1000,(100,3))
d

array([[804, 985, 151],
       [376, 763, 916],
       [379, 206, 921],
       [214, 440, 492],
       [428, 361, 923],
       [241, 484, 185],
       [993, 622, 723],
       [368,  72, 134],
       [ 50, 712, 198],
       [367, 560, 827],
       [419,  73, 339],
       [566, 340, 438],
       [178, 718, 235],
       [ 21, 603, 863],
       [764, 386, 912],
       [810,  51, 995],
       [967,  90, 492],
       [ 20, 902, 280],
       [377, 253, 523],
       [127, 702, 755],
       [227, 933, 562],
       [943, 601, 675],
       [552, 351, 976],
       [655, 378, 468],
       [461, 259, 483],
       [ 83, 750, 968],
       [996, 651, 748],
       [875,  19, 429],
       [762, 945, 578],
       [810, 406, 932],
       [387, 448, 983],
       [264,  40, 423],
       [703, 131, 986],
       [394, 968, 230],
       [379, 316, 211],
       [325, 587, 770],
       [799, 324, 502],
       [306, 728, 845],
       [404, 508, 505],
       [439, 297, 458],
       [347, 795, 711],
       [201, 276

In [82]:
q=range(1000)
q

%timeit [i//2 for i in q]

161 µs ± 8.21 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [83]:
p=np.arange(1000)
%timeit p//2

5.4 µs ± 126 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
